### ISSUE TITLE
org-ify the docs

### ISSUE THREAD

**Issue by canweriotnow** [exercism/xlisp#101]
Continuing in the grand tradition of xelisp, xclojure, and xscheme, any objection to moving the markdown docs to org-mode? I'd be happy to take it on.

**Comment by wobh** [comment]
Go for it!

**Comment by verdammelt** [comment]
+1.

**Comment by verdammelt** [comment]
@canweriotnow any update on this?

**Comment by verdammelt** [comment]
closing due to lack of interest.

**Comment by yurrriq** [comment]
Note that there are some quirks wrt `docs/*.org` but @kytrinyx has implemented a workable hack.
