### ISSUE TITLE
"point-mutations" is deprecated in favor of hamming

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xlisp#104]
This happened a while back, and it was for really weird legacy reasons.

I've since fixed the underlying issues that caused the problem, but for consistency
it would be nice to rename point-mutation to hamming, so that all the tracks are using
the same exercise name.

Once the problem has been renamed, I can run a script on the website to point people's
existing point-mutations solutions to the new hamming exercise so that they'll be able
to review solutions to hamming, and people who solve the new hamming exercise can see
all the old ones.

**Comment by verdammelt** [comment]
So at first glance we'll need to:

* change the production code file name from `dna.lisp` to `hamming.lisp`
* likewise change the production code package
* change the test code package from `point-mutation-tests` to `hamming-test`
* change the name of the directory
* change config.json

@kytrinyx Has any of the description of the problem changed? All the tests we have are faux DNA sequences. Also the main function has a documentation string mentioning DNA, as well as arguments (unimaginatively) named: `dna1`, `dna2`.

**Comment by kytrinyx** [comment]
No the description of the problem hasn't changed, nor has the inputs/outputs (faux DNA is fine, and dna1, dna2 sounds perfectly reasonable).

**Comment by wobh** [comment]
Uh oh. Looks like I needed to work on this a bit sooner? http://exercism.io/submissions/a04719ddd9f34322805ca1dd91ea143f

What if I do it now?

**Comment by verdammelt** [comment]
Hmm... didn't realize there was a deadline. I thought those submissions looked familiar :/

**Comment by kytrinyx** [comment]
No, that is totally my bad. I completely and utterly screwed up. I'll see if I can sort this out today (give me an hour or so).

**Comment by kytrinyx** [comment]
OK, I think this should be tidied up.

**Comment by wobh** [comment]
Changing the production package name means updating the tests to use `hamming:hamming-distance`. I would prefer `hamming:distance`. However  I find myself compelled to generalize a bit, as though the demonstration problem is one about DNA (a test metaphor, if you will) and `hamming` is just a package it uses (it could also have a `hamming:weight`. PR coming soon.

**Comment by kytrinyx** [comment]
`hamming:distance` is great. Any way we can make it so?

**Comment by wobh** [comment]
Made so. The PR is how I would prefer it, after I did some additional tidying up.

I've become ambivalent about the variable names in the stub as discussed above. The example is okay by me--it's basically what I would do, but I left the variable names in the stub as `dna1` and `dna2` to be consistent with the DNA metaphor established in the README.
