### ISSUE TITLE
binary: improve tests for invalid numbers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xlisp#111]
We should have separate tests for:

- alphabetic characters at the beginning of a valid binary number
- alphabetic characters at the end of a valid binary number
- alphabetic characters in the middle of an otherwise valid binary number
- invalid digits (e.g. 2)

If the test suite for binary has test cases that cover these edge cases, this issue can safely be closed.

See https://github.com/exercism/x-common/issues/95

**Comment by wobh** [comment]
The test suite doesn't cover these cases.

One wrinkle. A submission might use the standard `parse-integer` which would allow an optional `+` or `-` to precede the number and whitespace on either side. Further `parse-integer` has a `junk-allowed` flag so that it will parse the first contiguous numerals it finds in the string (and `+` or `-` preceding as before).

http://l1sp.org/cl/parse-integer

**Comment by verdammelt** [comment]
These new requirements will make it more complicated than simply using `parse-integer`

**Comment by kytrinyx** [comment]
@verdammelt is that a bad thing? The original reason I added this was for newbie programmers to actually have to figure out how binary numbers work.

**Comment by wobh** [comment]
I think it's also good for newbies to understand and use standard tools. I often see (and write) other iterations that implement the exercise more literally. We're also discussing it here: https://github.com/exercism/xlisp/pull/107

**Comment by kytrinyx** [comment]
There are other exercises that assume binary and would be good to use the standard tools for (secret handshake, I think, does this. Also maybe allergies, though I think maybe that's just bitwise, so the inputs are decimal but you're expected to think about them in binary).

**Comment by kytrinyx** [comment]
See https://github.com/exercism/x-common/issues/279

**Comment by verdammelt** [comment]
@kytrinyx good timing - i was *literally* (and I do mean *literally*) about to work on this issue. How did you know?

**Comment by kytrinyx** [comment]
Hah! That's a delightful coincidence. I've been catching up on email for three days straight, basically, and just accidentally got to this one.

**Comment by verdammelt** [comment]
Decided to go ahead and push these changes anyway. Not sure how long getting `all-your-base` exercise out the door will take (ref: [exercism/x-common#279](https://github.com/exercism/x-common/issues/279)

**Comment by kytrinyx** [comment]
Yeah, good call. It could be a while.
