### ISSUE TITLE
My progress of Common lisp is 30/29 (103%) 

### ISSUE THREAD

**Issue by fu7mu4** [exercism/xlisp#119]
Lisp is power full language ! 
It exceed the limit !

What should I do ? 

<img width="722" alt="2016-06-22 22 38 13" src="https://cloud.githubusercontent.com/assets/1885537/16268761/88217460-38ca-11e6-92e3-2c60f37d49ec.png">

**Comment by verdammelt** [comment]
Because Common Lisp is an awesome language and you can do that much more with it.

**Comment by verdammelt** [comment]
This is our 'official' list of exercises: what is the extra one you have done?

`[ "allergies", "anagram", "atbash-cipher", "beer-song", "binary",
"bob", "crypto-square", "difference-of-squares", "etl", "gigasecond",
"grade-school", "grains", "hamming", "leap", "meetup",
"nucleotide-count", "phone-number", "prime-factors", "raindrops",
"rna-transcription", "robot-name", "roman-numerals", "scrabble-score",
"sieve", "space-age", "strain", "triangle", "trinary", "word-count"]`

(You should be able to compare this list against the directories under under the `lisp` directory wherever you keep your exercism exercises.)

**Comment by verdammelt** [comment]
@kytrinyx Just wanted to pull you in to see this. Should we file a issue on the exercism website repo?

**Comment by verdammelt** [comment]
For the record: I too have gone beyond the mere limits of counting with the use of Common Lisp: 30/29 exercises completed.

**Comment by kytrinyx** [comment]
Ahh, yeah, that would be why.

I need to put a cron job in place to "move" (ish) implementations of exercises that have been renamed, I think.

And maybe we should not count exercises that aren't listed in the official list.

Yeah, we should probably have an issue about this in the exercism.io repository.

**Comment by fu7mu4** [comment]
the Point Mutations is missing exercises !

2016-06-23 17:34 GMT+09:00 Katrina Owen <notifications@github.com>:

**Comment by kytrinyx** [comment]
OK, so lisp no longer has any exercise 'point-mutations', however there are still submissions that are listed under 'point-mutations' (78 people have submitted a total of 171 iterations).

So migrating this will probably fix some part of this, but I suspect that it will not fix all the problems with it.

There's some stuff in the works with respect to deprecating exercises. See https://github.com/exercism/discussions/issues/40

**Comment by verdammelt** [comment]
So I'm going to close this issue.

@fu7mu4 Since you have done 103% of the exercises ( :) ) would you be interested in helping to create new ones?
