### ISSUE TITLE
Replace CIM (deprecated)

### ISSUE THREAD

**Issue by verdammelt** [exercism/xlisp#138]
CIM has been deprecated by its author (http://keens.github.io/blog/2017/01/29/deprecating_cim/) Our build uses this tool. Perhaps switch to roswell (https://gist.github.com/fukamachi/52dce85caf477043ffeb)

**Comment by wobh** [comment]
I'm reviving this and will work on it this week. Roswell looks like an excellent replacement, and seems like it'll be good for TravisCI. I also think having this in place will be useful for local xlisp development, such as for #140.

**Comment by verdammelt** [comment]
Thank you @wobh I haven't had time for much work on xlisp lately at all.

**Comment by wobh** [comment]
A great sign! https://travis-ci.org/wobh/xlisp/builds/231021325

**Comment by verdammelt** [comment]
Believe this is covered by #151  so closing.
