### ISSUE TITLE
Override probot/stale defaults, if necessary

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xlisp#146]
Per the discussion in https://github.com/exercism/discussions/issues/128 we
will be installing the probot/stale integration on the Exercism organization on
April 10th, 2017.

By default, probot will comment on issues that are older than 60 days, warning
that they are stale. If there is no movement in 7 days, the bot will close the issue.
By default, anything with the labels `security` or `pinned` will not be closed by
probot.

If you wish to override these settings, create a .github/stale.yml file as described
in https://github.com/probot/stale#usage, and make sure that it is merged
before April 10th.

If the defaults are fine for this repository, then there is nothing further to do.
You may close this issue.

**Comment by verdammelt** [comment]
@kytrinyx excellent this will help ping me about things. Nothing currently should trigger it, but there is something that will trigger by the end of this month.

I will check the settings - perhaps to give more leeway before closing.

**Comment by verdammelt** [comment]
Reviewed defaults and have decided to leave them alone. Can change later if we want. Closing.

**Comment by kytrinyx** [comment]
I made a mistake.

This was not explicitly documented in the README, but probot/stale **requires the presence of a .github/stale.yml** file.

If you want the default behavior, you need to add an empty .github/stale.yml file to this repo, otherwise the bot will not be active.

**Comment by verdammelt** [comment]
@kytrinyx  > I made a mistake

oh! *shakes fist*

OK, I'll go and create one of those...

**Comment by verdammelt** [comment]
done and done again.

**Comment by kytrinyx** [comment]
🌻 much appreciated!
