### ISSUE TITLE
TravisCI tests not running.

### ISSUE THREAD

**Issue by wobh** [exercism/xlisp#149]
See https://travis-ci.org/exercism/xlisp/jobs/230592144

When we updated the format of the `config.json` we didn't update the way the list of exercises gets extracted out of it in `xlisp-test`. With a `nil` value for `*exercises*` the test suite silently succeeds.

There will be two pull requests.

The first will add code that makes `xlisp-test` fail when `*exercises*` is `nil`.

The second will correctly extract the exercise name from `config.json`.

**Comment by wobh** [comment]
I guess there will just be one PR? When I updated my master branch, it updated the first PR to work.

**Comment by verdammelt** [comment]
Good catch and how embarrassing.

**Comment by wobh** [comment]
Pretty much my favorite kind of bug.

In summary:

https://travis-ci.org/wobh/xlisp/builds/230969489 shows that the `xlisp-test:test-exercises` fail if `*exercises*` is `nil` before the test run (note: error status was later changed to `3`).

https://travis-ci.org/wobh/xlisp/builds/231007721 shows the build passing with tests running.
