### ISSUE TITLE
Implement Lisp Exercises

### ISSUE THREAD

**Issue by verdammelt** [exercism/xlisp#23]
This is a placeholder issue for keeping track of porting assignments to Lisp, or noting why they may not be applicable. (This list shamelessly stolen from https://github.com/exercism/xclojure/issues/1)

- [X] bob
- [X] word-count
- [X] anagram
- [X] beer-song
- [X] nucleotide-count
- [X] rna-transcription
- [X] point-mutations
- [X] phone-number
- [X] grade-school
- [X] robot-name
- [X] leap
- [X] etl
- [X] meetup
- [X] space-age
- [X] grains
- [X] gigasecond
- [X] triangle
- [X] scrabble-score
- [X] roman-numerals
- [X] binary
- [x] prime-factors
- [X] raindrops 
- [X] allergies
- [X] strain
- [X] atbash-cipher
- ~~accumulate~~
- ~~bank-account~~
- [X] crypto-square
- [ ] trinary @verdammelt
- [x] sieve
- [ ] simple-cipher
- [ ] octal
- [ ] luhn
- [ ] pig-latin
- [ ] pythagorean-triplet @wobh
- [ ] series
- [X] difference-of-squares
- [ ] secret-handshake
- [ ] linked-list
- [ ] wordy
- [ ] hexadecimal
- [ ] largest-series-product
- [ ] kindergarden-garden
- [ ] binary-search-tree
- [ ] matrix
- [ ] robot-simulator
- [ ] nth-prime @wobh
- [ ] palindrome-products
- [ ] pascals-triangle @wobh
- [ ] say
- [ ] sum-of-multiples
- [ ] queen-attack
- [ ] saddle-points
- [ ] ocr-numbers

**Comment by wobh** [comment]
How do you want to divvy these up? There's a number of simple ones, we should probably try to get out sooner rather than later: roman numerals, difference of squares, nth-prime, pascals triangle, raindrops, and probably others. They can be cycled earlier into the list of existing exercises.

**Comment by verdammelt** [comment]
Maybe we can just note down when one of us 'takes' one to do it. Then handle the submission via pull request?

**Comment by wobh** [comment]
Got "difference of squares" almost ready. Roman numerals next.

**Comment by canweriotnow** [comment]
PR #45 should check off 'raindrops'

**Comment by wobh** [comment]
So, I've been away from exercism and xlisp for a while due to health problems and other stuff, but I'm getting back into it. I'd like to hold off a bit on new exercises until we can check off the second box, it's subtasks and third box in #26. 

I made some headway on that back in January here: https://github.com/wobh/xlisp/tree/xlisp-26-test-lib so I believe we're *really* close.

**Comment by verdammelt** [comment]
Been away from xlisp for a while as well. Maybe coming back now. Need to clean up old business I left behind here (and give some nits on exercism!)

**Comment by wobh** [comment]
For future reference:
- all exercises implemented by language: http://synopsis.exercism.io
- all exercise readme's: https://github.com/exercism/x-common

**Comment by yurrriq** [comment]
Oh, cool. Would it be aright if I snagged a couple?

**Comment by wobh** [comment]
Sure!

**Comment by yurrriq** [comment]
Sweet. I'll stick my username next to those I plan to implement in the list then PR.

**Comment by kytrinyx** [comment]
We have a new process that you can use to find exercises to implement.
You can read all about it [here](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track).

I'm closing this issue in favor of the process described in the Contributing guide linked to above.

Thanks!
