### ISSUE TITLE
Travis Integration

### ISSUE THREAD

**Issue by verdammelt** [exercism/xlisp#26]
Thought it would be good to get a real travis integration. Maybe that is possible?

- [x] Travis Badge for README
- [ ] Travis job to run tests (with sbcl for example)
  - [ ] install sbcl
  - [ ] install quicklisp
  - [ ] install lisp-unit
- [ ] solve problem of the tests loading files that do not exist (example files are named `example.lisp`)
- [ ] ???
- [ ] profit.

(*note* IMNSHO it would be cool to have the build script, once sbcl &c. are installed be written in Lisp)

**Comment by wobh** [comment]
@verdammelt (cc @kytrinyx) It took me way too long to think of this, but the "dumbest thing thing that could possibly work" to get the tests to run on the example files is this: symbolic links. Our test script just has to check that the starter slug file is a symbolic link and if not, blow it away with a symbolic link to `example.lisp`. Then it runs the tests with `sbcl --load exercise-tests.lisp`.

I don't know how Travis figures out whether the lisp tests pass, but presumably it does somehow, I can look into that. Certainly there could be other drawbacks too. I'll do some local testing when I have time.

**Comment by kytrinyx** [comment]
Some of the other tracks use a temporary directory and rewrite files. I don't think that matters on travis, but should anyone run the full test suite locally before committing, blowing away a stub file and having it be a symlink to the example could be problematic.

**Comment by wobh** [comment]
I've come up with something better, dumber:

```common-lisp
(loop  
  for demo in (directory "./*/example.lisp")
  for test in (directory "./*/*-test.lisp")
  do (progn (load demo) (load test)))
```

**Comment by verdammelt** [comment]
That won't work because the test file actually calls `load` on the code file.

**Comment by wobh** [comment]
Ah, but the tests are run on the package, not the file. If we skip past the load error the tests run against the definitions in example file loaded earlier. I've been working with this for a while now and I'm now 80% sure we can hack up something that'll work.

A couple of challenges and possibilities so far:

- Clisp's file error has so-far been uncatchable. This might be a bug in clisp. However, it seems we can catch the file-error raised in ccl and sbcl.
- `*default-pathname-defaults*` is set to an empty path in ccl, but to the pathname lisp was started in in sbcl and clisp. In any case I think we can set it, in advance of loading the testfile, which should have the effect of changing the working directory for `load`. As long as we provide a stub code file, this would avoid load errors.
- Worst case scenario (not so bad): we have to change all the and test files to do some environmental setup when loaded. For example: the test file could check the value of a parameter like `*xlisp-test*` and if it's set, skip loading the code file. The xlisp testing script would set that parameter, and start loading things as above.

**Comment by wobh** [comment]
I got the craziest errors trying to use an alternate value for *default-pathname-defaults* in clisp. I'm thinking about a variation of the third "worst-case" option, where we could use the module system and `require` instead of load. I would love to work out a mostly stable way to catch file errors though. I have other plans for that.

**Comment by wobh** [comment]
Why reinvent the wheel? https://github.com/luismbo/cl-travis
Builds on this nifty project: https://github.com/KeenS/CIM

**Comment by verdammelt** [comment]
@wobh Those look interesting.

**Comment by wobh** [comment]
I'm about to start experimenting with them in a branch. I have just worked out what seems like a reasonably good way to run all the test specs. I don't think it's quite ready for a pull request yet, @verdammelt you should at least look in https://github.com/wobh/xlisp/tree/xlisp-26-test-lib and let me know what you think, so far.

**Comment by verdammelt** [comment]
@wobh have you been able to check into cl-travis? How can I help on this issue?

**Comment by verdammelt** [comment]
@wobh What is the state of this? What is working and what is not? I'd like to help if I can.

**Comment by wobh** [comment]
So I got CIM setup and I was able to run all the tests in this branch with `cl -f bin/xlisp-test.lisp -e "(xlisp-test:run-tests-all)"` which isn't great but it works. So I think I just have to setup CL Travis and push.

I'm also not entirely wild about the changes I had to make to the test files to make the test suite run. I'll try to get a branch on Travis the runs the test suite and see what we think then.

**Comment by wobh** [comment]
The tests fail! https://travis-ci.org/wobh/xlisp/jobs/63280830

This is great! *does a little jig*

**Comment by wobh** [comment]
Tests are running and passing, but that seems to be because the test runner doesn't care about failing specs. Have to think about how to make sure the test runner does the right thing with errors and failures. Meta: Might have to come with a test-self-test to ensure future development doesn't break this expectation.

**Comment by verdammelt** [comment]
The test files are set up to make running the tests on load easy - but the results are not kept or returned, just dumped to *standard-output*.

Perhaps we should be loading all files and *then* running all the tests for CI? That way we can pass/fail the build upon the results of running the tests...

**Comment by wobh** [comment]
Welp, the CI tests fail, but not for the reason they fail locally. https://github.com/wobh/xlisp/tree/xlisp-26-test-lib

I'm out-of-brain for figuring this out for the time being.

**Comment by wobh** [comment]
I'm sure this is something dumb, but I just don't see what could be causing it. I'm about to start committing little print statements to see what's going on. https://travis-ci.org/wobh/xlisp

**Comment by wobh** [comment]
Okay! Removed spurious path in excluded paths list and now the tests are failing for the expected reasons.

**Comment by wobh** [comment]
This is great! Now it looks like we have some actually failing specs on different lisp implementations. SBCL passes everything, but CCL and ECL don't like something about 99 bottles tests, and Clisp is unhappy loading ETL-TEST package.

We could use some better test reporting, perhaps figure out how to only print failing specs, but I think CI has arrived for xlisp.

**Comment by verdammelt** [comment]
That's great! Should we turn it on for all 'known good' implementations and then open issues for the ones that don't currently work?

I still don't quite like needing to use a feature toggle for loading the example file; I'm slowly thinking of a way around it (involving consistent naming so we can move files at test build time) - but I don't want to stop this issue in the meantime.

**Comment by wobh** [comment]
The feature test seems like the simplest solution by a long shot. I'd be happy to get it down to one feature test though, something like:

```common-lisp
;; Affect `(export #:test-anagram)' in package definition

(defun test-anagram (filename)
  (load file)
  (let ((*print-errors* t)
	(*print-failures* t))
    (run-tests :all :anagram-test)))

#-xlisp-test (test-anagram "anagram")
```

Which would have other benefits.

**Comment by wobh** [comment]
I can't decide if we should merge this change in as-is to get any kind of integration testing going, and figure out what to do with the tests files separately, or try to figure that out so we can commit to something we can live with ASAP. Either way, we have to implement the rest of the tests differently. The two issues seem well entwined to me.

**Comment by verdammelt** [comment]
I suggest merging in the change with only the Lisps we know work across the board turned on. Then create issues for the others. Then perhaps another issue for improvements around handling of the test file. I think I'd rather get the build running than wait.

**Comment by verdammelt** [comment]
So, I think we can consider this issue done. I'll close it, we can open other issues if there are remaining/new items.
