### ISSUE TITLE
Need more exercises!

### ISSUE THREAD

**Issue by verdammelt** [exercism/xlisp#32]
Here are exercises from the xclojure project which are not yet implented in xlisp:
 
- [ ] scrabble-score
- [ ] roman-numerals
- [ ] binary
- [ ] prime-factors
- [ ] raindrops
- [ ] allergies
- [ ] atbash-cipher
- [ ] bank-account
- [ ] crypto-square
- [ ] kindergarten-garden
- [ ] robot-simulator
- [ ] queen-attack
- [ ] accumulate
- [ ] binary-search-tree
- [ ] difference-of-squares
- [ ] hexadecimal
- [ ] largest-series-product

(xclojure chosen rather arbitrarily as a place to get a list)

**Comment by kytrinyx** [comment]
Here's a full list of all the exercises in all the languages: http://synopsis.exercism.io/

**Comment by verdammelt** [comment]
Thanks for the link! Also those crazy Haskell people have been busy - looks like their list is the longest!

**Comment by kytrinyx** [comment]
Haskell is by far the most successful track in exercism in terms of quality, contributions, and discussions. I think it might be all due to @etrepum. If I can get my head above water I'd like to see if it's possible to reverse-engineer some of that goodness into the rest of the site.

**Comment by wobh** [comment]
Rationally, I know it's technically not necessary, but I have this mental block that I won't be able to work on developing new exercises until I've completed the existing ones. I get through the next two, and start work on the others.

**Comment by verdammelt** [comment]
@wobh I've got to stay ahead of you somehow, so I

**Comment by verdammelt** [comment]
I hate how I see the 'close and comment' button as a 'cancel' button and so do stupid things like close the issue when I only wanted to discard my comment.

**Comment by etrepum** [comment]
Not sure which of these things are why the track has done well, but I'll save you some trouble:

* ported as many exercises as I could get my hands on at the time (haven't kept up with new exercises though)
* consistently provided prompt (<24hr) feedback to all submissions that haven't had any
* tried to include rationale and/or references for feedback when possible, it's important to know why something should be improved
* generally refrained from providing full answers, give people an opportunity to discover things for themselves

**Comment by etrepum** [comment]
Although I have fell behind a bit since I've been on holiday for three weeks, it appears that others have been picking up the slack :)

**Comment by verdammelt** [comment]
@etrepum thanks for the ideas of how to make a successful track. I am still surprised that this track even got *started* let alone seems to be done pleasantly. I'm starting to see other users commenting on each other's submissions which I take as a good sign.

**Comment by verdammelt** [comment]
Not sure why I felt the need to duplicate #23. I guess I totally forgot I already had an issue for make more exercises.

**Comment by kytrinyx** [comment]
The things you've done on Haskell are what I did on Ruby for the first month, but then there were simply too many new submissions every day, and I had to give up the 24 hour SLA. That's over a year ago, and things got completely out of hand since.
