### ISSUE TITLE
Enable testing in CI for ECL

### ISSUE THREAD

**Issue by wobh** [exercism/xlisp#57]
- [ ] fix failing spec in Beer Song https://travis-ci.org/exercism/xlisp/jobs/65655348#L3926
- [ ] remove `ecl` from `allow_failures` in `.travis.yml`

See https://github.com/exercism/xlisp/pull/54#issuecomment-108839095 and https://github.com/exercism/xlisp/issues/55

**Comment by verdammelt** [comment]
Fixed by #60
