### ISSUE TITLE
Update contributing documentation with info about using CIM

### ISSUE THREAD

**Issue by wobh** [exercism/xlisp#58]
Basically,
1. Install CIM
2. Install lisps
3. Install Quicklisp
4. --Run all the tests locally--

See https://github.com/KeenS/CIM

**Comment by verdammelt** [comment]
I had problems with CIM in that I already had QuickLisp installed and CIM didn't seem to see it. As far as I can tell CIM expects a quicklisp directory inside of $CIM_HOME. This seems awfully presumptuous of it :).

I made it work by symlinking my ~/.quicklisp to ~/.cim/quicklisp.

So now that I've solved that mystery I *could* write up the instructions - but perhaps instructions on how to install CIM/Lisps/QuickLisp in the 'normal' way might work better?

For the record: I installed SBCL via homebrew, QuickLisp, then CIM, then more implementations via homebrew. I am guessing this is not the 'correct' way.

Also note: the item about how to run items locally is handled already by my changes to the README.

**Comment by yurrriq** [comment]
Mildly related questions:
- Is there a CIM equivalent for scheme? I often find I need to switch between chicken, gambit, guile and racket.
- Is there a good way to get gambit and Ghostscript to coexist peacefully?

**Comment by verdammelt** [comment]
Been pretty quiet on this issue lately. If no one else wants to write this up I'll pick this up and try to figure out the 'right' way of installing CIM.

**Comment by verdammelt** [comment]
I finally got around to trying to use CIM directly and boy am I now annoyed. Maybe we shouldn't suggest CIM? It may not be worth it... have other people had good luck with it? 

Just now it would not install clisp-2.49 (had to install clisp-head). There is no update option for the lisps it installs. it does not consistently install quicklisp in all lisps. I purged all installs and tried to re-install sbcl via brew (which succeeded) but then coulnd't get CIM to work properly with sbcl-system. grrr.

**Comment by yurrriq** [comment]
I've had similar experiences, @verdammelt :/

**Comment by wobh** [comment]
Okay, lets look at our options.

**Comment by verdammelt** [comment]
Funny thing is CIM seems to work nicely when I had it set up. I had it set up with all HomeBrew installed implementations and with QuickLisp installed by hand and symlinked into the CIM directory. That let me use it as we do for testing. But trying to use it as a Lisp Implementation manager system ala RVM/RBENV, etc. etc. I don't think that's going to work.

I'll try to take a moment to fix my setup (probably re-installing CIM) and then I might suggest that *that* setup be one that suggest for contributors.

(I just checked out cl-travis and it looks like it only uses CIM to install ACL, all the others it installs itself and then does `cim use`.)

**Comment by verdammelt** [comment]
OK, so I think that I'd be "ok" suggesting using CIM to run across multiple instances - but not to install those instances. These instructions are for contributors - not for users of the track so a little extra WTF-ery might be acceptable.

While it is not a great tool - it is ATM *the* tool to run lisp code across several implementations, which will help contributors contribute.

**Comment by yurrriq** [comment]
:+1:

**Comment by yurrriq** [comment]
I just stumbled across this project, which may be useful now or in the future: https://github.com/roswell/roswell

**Comment by verdammelt** [comment]
The Roswell readme says: 

> It now has evolved into a fullstack environment for Common Lisp development, testing, code sharing and app distribution which might push the CL community to a whole new level.

That is a LOT more than we need. That is why I decided I didn't like it a while back. Seemed to be doing too much...

**Comment by yurrriq** [comment]
I thought remembered it coming up here before. Well CIM as a tool for running across multiple instance sounds good to me still.

**Comment by wobh** [comment]
Closed in #98
