### ISSUE TITLE
xlisp-test: load example files for tests, not in advance

### ISSUE THREAD

**Issue by wobh** [exercism/xlisp#64]
See #63.

One solution might be adding a readtime conditional above `defpackage` for the `dna` package example files.

But it makes sense to take this opportunity to change how "xlisp-test" loads test data from example files. It should probably load the examples like test data, before the test is run, then afterwards using `delete-package` on the example package.

**Comment by verdammelt** [comment]
How about we have xlisp-test load the test and the example files before the test run and then cleanup both afterwards. That will keep each test run as independent as possible from each other.

**Comment by wobh** [comment]
https://github.com/exercism/xlisp/pull/65

Not sure why it isn't referencing here. Also, not sure why all the previous commits I rebased seem to be coming along with it. Shouldn't be harmful, though. 

http://stackoverflow.com/questions/5415560/github-pull-request-without-old-commits

**Comment by wobh** [comment]
With #65 merged, I think we can put this to bed.
