### ISSUE TITLE
Generated TOML files are invalid

### ISSUE THREAD

**Issue by verdammelt** [exercism/xlisp#650]
It appears that generated TOML files for practice exercises are invalid. They contain lines like `description = blah blah` but the value should be quoted `description = "blah blah"`

This causes `configlet sync` to crash. (Unfortunately this problem is not being caught by `configlet lint` - I have filed an issue about it (https://github.com/exercism/configlet/issues/613)

**Comment by verdammelt** [comment]
@PaulT89 I will be pushing a PR to fix this (along with some real sync issues) but could you correct the generator please. Thanks.

**Comment by verdammelt** [comment]
Configlet sync can create the stub of a practice exercise if the exercise is in the track's `config.json`:

1. Add exercise info to `config.json` - slug == SLUG
2. ./bin/sync-exercise SLUG

This creates the directory along with .meta & .doc sub-directories.

**Comment by PaulT89** [comment]
Oops, sorry about that.  I've fixed the generator and put in a PR.

> Configlet sync can create the stub of a practice exercise if the exercise is in the track's `config.json`

Yeah, the track's `config.json` is the one thing that the generator absolutely does not touch.  I had a few reasons, but chief among them:

1. I was thinking "If I break that, I won't just break one exercise - I'll break _everything_".
2. The json decoder in python dumps everything into a dictionary, and while I think Python dictionaries are actually ordered these days, I don't know _how_ they're ordered (i.e. alphabetically?  As it appears in the file?).  The prospect of my generator rearranging the entire `config.json` file seemed needlessly daunting.

There are other reasons as well, but the gist of them all is that it seemed more trouble than it was worth.  Instead, making the generator the one-stop shop for generating all the files seemed like the easier path to take.

**Comment by verdammelt** [comment]
Fixed by #653
