### ISSUE TITLE
DOC: emacs setup

### ISSUE THREAD

**Issue by wobh** [exercism/xlisp#69]
We get enough misformatted submissions the I think we should take the hint and add some super basic documentation about setting up Emacs for exercism exercises. This might also help with the Clojure, Scheme, Elisp, and nascent LFE tracks. We might even want to go so far as a minor mode.

@verdammelt, @canweriotnow what do you think?

I don't think I know any maintainers of the Clojure or LFE, so if you do and think they'd be interested in this too, we should send them a shout-out.

cc @kytrinyx

**Comment by verdammelt** [comment]
Great idea. To discuss here something you mentioned there(http://exercism.io/submissions/75d8b707969d446e92c27cf09f30dd2b).

> Look up how to set it on a per mode, or even per project basis.

Emacs doesn't have a concept of projects. Of course some add-ons create this concept but Emacs only knows about per-mode, per-buffer (buffer local variables), per-file (file variables), and global.

I'd suggest something like:

```
(defun setup-lisp-indent () (setq indent-tabs-mode nil) 
(add-hook 'lisp-mode-hook 'setup-lisp-indent)
```

(I also prefer naming the hook methods so that it is easy to remove them from the hook later.)

**Comment by canweriotnow** [comment]
@wobh I think it's a great idea... and since @kytrinyx recently asked me to jump in on maintaining Clojure, I'll speak for that track with a resounding "yes" - I wrote a blog post on doing just that that I can adapt.

I'm thinking that maybe once I get back to work on exercism.el putting some sensible defaults in there would be a good idea.

Also: there's an LFE track in the works!?!?! Awesome!

> Emacs doesn't have a concept of projects. Of course some add-ons create this concept but Emacs only knows about per-mode, per-buffer (buffer local variables), per-file (file variables), and global.

All the more reason to use Projectile :)

I would actually suggest suggesting people getting started with emacs use a set of sensible defaults like Prelude (my personal choice) or emacs-live.

**Comment by kytrinyx** [comment]
Resounding "yes" from me :) Anything that will help with consistency!

**Comment by verdammelt** [comment]
@canweriotnow "...I wrote a blog post..." 

Link please?

**Comment by wobh** [comment]
This is driving me a little bonkers. I used to have something that only turned off indent-tabs-mode for certain things, but I can't remember how. The only thing I can think of is, perhaps I had been using [direnv](http://www.direnv.net) to set an environment variable in my exercism exercises directory, that Emacs used. However, I think I had something rigged up from before I knew about direnv. I don't think it was [directory local variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html) because I'm pretty sure I've never used those, but maybe I did one time?

**Comment by verdammelt** [comment]
Since we provide a starter file for each exercise we could simply put a 
```
;; -*- indent-tabs-mode: nil -*-
```
at the top of the file. 

Even though I just suggested that - I don't think I really like it.

**Comment by wobh** [comment]
There's no bad ideas in brainstorming.

**Comment by verdammelt** [comment]
I can't remember - does Emacs warn the user when they open a file with File Variables? I feel like I see that happens *sometimes* but I don't know when it does, or when it doesn't.

**Comment by wobh** [comment]
I get warnings about them.

**Comment by canweriotnow** [comment]
@verdammelt Sorry for not paying attention for 10 days... actually two posts, of varying utility:

[Welcome to The Dark Side: Switching to Emacs](http://decomplecting.org/blog/2014/10/23/welcome-to-the-dark-side-switching-to-emacs/)

[Emacs: Down the Rabbit Hole](http://decomplecting.org/blog/2014/10/30/emacs-down-the-rabbit-hole/)

Also, it's a little more specific to Clojure, but still a great resource - [Clojure for The Brave and True: Start Using Emacs](http://www.braveclojure.com/basic-emacs/)

Also, everyone should read [Emacs Redux](http://emacsredux.com/), possibly the most pragmatic emacs blog out there.

Enough links for you? :smiling_imp:

**Comment by yurrriq** [comment]
Re: file variables.

It seems putting them at the end of the file would be less invasive-feeling.

I work with a Vim guy and he's been more amenable to EOF than BOF.

```lisp
;; Local Variables:
;; indent-tabs-mode: nil
;; End:
```

**Comment by yurrriq** [comment]
I think an exercism minor mode would probably be best and would be willing to help with it, if needed.

**Comment by verdammelt** [comment]
Doing a little issue maintenance so I wanted to toss in my US$0.02:

I think the instructions should explain how the exercism widget works (spaces only indentation) and then give examples of how to do that in Emacs (maybe VI?). But the examples should show how to do it in the stock editor - not in some starter-kit or with xyz package installed.

It could also mention an exercismio-mode if such exists, perhaps even recommend it.

**Comment by yurrriq** [comment]
Note to self: consider mentioning the lfe-mode.el that ships with LFE. Also inferior-lfe.

**Comment by yurrriq** [comment]
I think we should definitely mention lispindent across he lisp family.

**Comment by verdammelt** [comment]
@yurrriq yes `indent-tab-mode` is an important setting for all the lisp flavored tracks on Exercism.IO

**Comment by verdammelt** [comment]
Just poking in here to see if there is any movement.

I think the best suggestion would be to add to the setup guide a subsection explaining how the widget on the site only works with space indentation and then add some instructions for emacs & vim.

If there are no further ideas I'll put this on my list to do.

**Comment by wobh** [comment]
Sounds good to me. Thanks!

**Comment by verdammelt** [comment]
OK, I am assigning this to myself.

**Comment by yurrriq** [comment]
I wonder if we could somehow separate this into two documents: One polyglot, for setting up Emacs and generic Lisp stuff, and another per track-specific details with language-specific details. It seems like there's lots of crossover among the Lisp family, but I would imagine other tracks might like a "here's an awesome editor that you can allow to take over your life."

**Comment by kytrinyx** [comment]
@yurrriq I'm not quite sure what the generic need is. If it's emacs stuff or editor or IDE stuff in general, maybe we can add something directly to exercism.io https://github.com/exercism/exercism.io/tree/master/x/docs/md

Then we can include it in all the tracks.

**Comment by verdammelt** [comment]
@kytrinyx There is a general need to point out to people that the code widgets on the site don't interpret tabs well; not sure how big of a deal it has been in other tracks but it comes up often here in Lisp-land.

**Comment by kytrinyx** [comment]
ah. What would "interpret tabs well" look like? In Go we use tabs for indentation, and they're shown as 8 spaces on the site. We don't use tabs for anything else, though, so I don't know what it would look like to mix tabs and spaces within the code.

**Comment by verdammelt** [comment]
Actually, now that you say that, it is the *mixing* that is the problem. Emacs, by default will gladly mix tabs and spaces. While we modern people think that is an abomination, Emacs has, I'm sure, some insrcrutable reason, it is after all the best editor ever :)

(Likewise Emacs also insists upon two-spaces for sentence ending - I can understand its reasons, but have also "corrected" its misconception about that :). I'm just glad it is such a flexible editor that I can change the tool to fit my hand so well).

I'm going to quickly edit the doc to point out it is the mixing of tabs and spaces that is the concern. Thanks for jogging my memory and letting us clarify the issue.

**Comment by wobh** [comment]
I'm just going to leave this here; https://www.emacswiki.org/emacs/SmartTabs
