### ISSUE TITLE
CI:ECL: `load` with `:verbose` and `:print` options writes text of file unsafely

### ISSUE THREAD

**Issue by wobh** [exercism/xlisp#77]
For the new `prime-factors` example I implemented a factorization wheel with a circular list. This became an issue with the ECL tests because ECL's `load` with `:verbose` and `:print` set to true (or possibly just one of those), like we use by default, prints the file to the screen, but does so with `*print-circle*` left at `nil`. If the file contained a circular list `load` would never finish.

This could be seen as a bug in `ECL` but I would like to come up with a work-around. It might be enough to set `*print-circle*` to `t` in `xlisp-test`. Before I download ECL and start tinkering with it, what do you think about this?

Failing job: https://travis-ci.org/wobh/xlisp/jobs/82872525

**Comment by verdammelt** [comment]
That sounds like an interesting implementation and I'd love to see it. (It does sound like it might go against my "don't be clever in example.lisp" pseudo-rule though...)

If setting `*print-circle*` to `nil` fixes it then do it in `xlisp-test` - perhaps under a feature test for ECL.

**Comment by wobh** [comment]
Let me know if you think it's too clever. 

https://github.com/wobh/xlisp/commit/198213441c88b0257f52609d312d2b9887ee4a67

I also added a bunch of tests.

**Comment by wobh** [comment]
It's definitely ECL's `load` with the `:print` option and setting `*print-circle*` to `t` makes it work as expected. Reviewing the spec for `*print-circle*` http://l1sp.org/cl/*print-circle* it seems like it would be fine to set it to `t` generally, and perhaps even a good idea.

**Comment by wobh** [comment]
A passing build: https://travis-ci.org/wobh/xlisp/jobs/83063702

I have two ideas here based on the same foundation.

First add some constants to label the verbosity levels. This takes care of an irksome remainder I decided not to do initially for some reason, but also makes distinguishing the two solutions a easier.

Solution 1. Set `*print-circle*` to `t` in the lexical scope of `load-package`. This is a minimal typing solution and the passing build above is the prime-factors exercise rebased onto that branch. At the bottom you can see the circular list printed correctly. The rationale here is that whatever the `load` outputs, it should be safe, so just set it to `t` and be done.

Solution 2. Set `*print-circle*` to the outcome of `(verbosity-p +debug+)` in the lexical scope of `load-package` and set the `load` `:print` argument to the same. This is a minimal effect solution, observing that the extra output of `load` with `:print` is not strictly desirable for general testing, and `*print-circle*` doesn't need to be any value not required.

I prefer solution 1 for the time being, but I think considering what solution 2 does for us is worth thinking about more generally. If/when we find another place to set `*print-circle*` to `t` or have to set it's dynamic value in `test-exercises` we can do so by verbosity level required with `verbosity-p`.

**Comment by verdammelt** [comment]
I agree - it looks like setting `*print-circle*` to `t` is a good idea. It is a good thing for a testing harness to do - given that there may be circular data - we'd want the harness to be able to handle and report on that without it having its own problems.

I go with solution 1. If we tied it to verbosity then we should consider the other `*print-x*` settings which might also be needed/useful. But I think the simpler approach is better for now.
