### ISSUE TITLE
allergies-test: Add a test for case-insensitivity

### ISSUE THREAD

**Issue by wobh** [exercism/xlisp#81]
Per discussion in http://exercism.io/submissions/c9f240b76eb248d9aeec1fd416ea51be we think adding a case-sensitivity test is a good idea.

The test should fail if `allergic-to-p` returns `nil` for score and corresponding allergens that are lowercase, mixed-case (including title-cased), or uppercase. Examples that should be true:

- `(allergic-to-p 0 "eggs")`
- `(allergic-to-p 0 "eGgS")`
- `(allergic-to-p 0 "Eggs")`
- `(allergic-to-p 0 "EGGS")`

**Comment by verdammelt** [comment]
+1.

If we had a 'low hanging fruit' tag I'd tag this with it.

**Comment by kytrinyx** [comment]
I made a low-hanging-fruit tag :)

**Comment by verdammelt** [comment]
@kytrinyx LOL - I love how you lurk everywhere on these projects and just pop in and do little things like this!
