### ISSUE TITLE
beer-song-test: Use FORMAT to generate test control string

### ISSUE THREAD

**Issue by wobh** [exercism/xlisp#86]
Per http://exercism.io/submissions/2b5d71f2d6234c498eb1a482c1071f05 file formatting of line endings in "beer-song-test.lisp" causes false negatives. For each line in verses, replace with `"~&~A~%"` and format.

For example https://github.com/exercism/xlisp/blob/master/beer-song/beer-song-test.lisp#L10: 

```common-lisp
(defparameter +verse-8+
  "8 bottles of beer on the wall, 8 bottles of beer.
Take one down and pass it around, 7 bottles of beer on the wall.
")
```

change to:

```common-lisp
(defparameter +verse-8+
  (format nil "~&8 bottles of beer on the wall, 8 bottles of beer.~%~
               ~&Take one down and pass it around, 7 bottles of beer on the wall.~%")
```

Likely this affects any other exercise we have or will have multi-line strings.

(bonus: aligned format not strictly necessary but a nice benefit of `~#\Newline` see http://l1sp.org/cl/22.3.9.3)

(bonus, rename parameters from `+parameter-name+` to `*parameter-name*`.)

**Comment by FungusHumungus** [comment]
Unfortunately the suggested solution results in the error -

     error in FORMAT: unknown format directive (character: Return)
      ~&8 bottles of beer on the wall, 8 bottles of beer.~%~
      ~&Take one down and pass it around, 7 bottles of beer on the wall.~%

Since with a windows encoding the line now ends with  `~#\Return#\NewLine` rather than `~#\NewLine`.

**Comment by wobh** [comment]
If you take out the escaped newline what then?

**Comment by FungusHumungus** [comment]
Then we are back to the original problem of these pesky ~#Return characters creeping in.

**Comment by wobh** [comment]
This SO thread from a couple years ago seems suggestive: http://stackoverflow.com/q/17926556. What implementation? Have you tried Clisp?

**Comment by FungusHumungus** [comment]
Interesting. I am trying both SBCL and CCL. I'll have a try with CLisp..

**Comment by wobh** [comment]
I recall CLisp having better support for Windows, and this backs that up: http://clisp.org/impnotes.html#clhs-newline

**Comment by FungusHumungus** [comment]
Yes have tried CLisp and it does not have this problem.

There are further differences in the implementations however, note the differences in the capitalization of the 'o' -

In CLisp

    > (format nil "~@(~A~)" "8 onk")
    "8 Onk"

In SBCL 
    
    > (format nil "~@(~A~)" "8 onk")
    "8 onk"

**Comment by verdammelt** [comment]
Is my pull request useful at all for this? I did it without reading the whole thread here...
