### ISSUE TITLE
robot-name-test: Use case indifferent tests

### ISSUE THREAD

**Issue by wobh** [exercism/xlisp#87]
I don't think it makes sense that robot "ZZ999" should be considered a different robot from "zz999" given the description of the problem. We should be able to easily write tests that don't require a particular normalization.

(Bonus: if they're still needed afterwards, replace `is-upper-alpha-p` with `upper-case-p` and `is-digit-p` with `digit-char-p`.)

**Comment by kytrinyx** [comment]
+1 this should definitely be case insensitive.

**Comment by verdammelt** [comment]
Looks like other tracks also check for two leading uppercase letters. Readme for the exercise implies this. I'l file an issue on x-common asking if this should be case sensitive or not. I'll also close this issue for until it is decided.
