### ISSUE TITLE
Track is missing an docs/ABOUT.md

### ISSUE THREAD

**Issue by verdammelt** [exercism/xlisp#89]
If you visit http://exercism.io/languages/lisp and then click on 'About the Common Lisp Track' it says "We're missing a short introduction about the language.". And to put that text into `docs/ABOUT.md`.

So I guess we need on of those.

**Comment by kytrinyx** [comment]
Yes, please :)

The idea behind the introduction is not to be wikipedia, but to tell people why they'd want to play with it.

**Comment by wobh** [comment]
Why would someone want to use Common Lisp? I know my reasons, but I expect them to be idiosyncratic.

**Comment by canweriotnow** [comment]
> LISP is worth learning for a different reason — the profound enlightenment experience you will have when you finally get it. That experience will make you a better programmer for the rest of your days, even if you never actually use LISP itself a lot. (You can get some beginning experience with LISP fairly easily by writing and modifying editing modes for the Emacs text editor, or Script-Fu plugins for the GIMP.)
— ESR

**Comment by verdammelt** [comment]
Why would anyone use Common Lisp?! :) All the cool kids are using Clojure, the academically minded are using some version of Scheme. Common Lisp was built by committee and that shows in spots.

Maybe I shouldn't write it? :)

I use Common Lisp for conscious and unconscious reasons. Its syntax is mostly sparse and clean, but not as far as Scheme goes. It has good support for any style of programming you want, whether that style had been around when it was standardized or not. It has a reasonably wide language set so there is very often the function you need there in the language. It does not attempt to solve the problem of unhygienic macros - which is a boon when you don't want them - but gives you the tools to write them if you want them. It has crazy little quirks that make me smile or say "WTF" (but not in bad ways like other languages (Looking at you CoffeeScript (most recently)) - like the `~R` directive to `format`. I think there is also some nostalgia I feel for this language which I've been playing with for so many years, lurking in `comp.lang.lisp`...

Every point above I could turn into a negative too probably. No language is perfect, and Common Lisp definitely isn't perfect (hash tables are a pain to use for example) - but I know that if I don't like something about this language I can add something myself and make it the language I want.

> "Lisp isn't a language, it's a building material."
>
> - Alan Kay

**Comment by kytrinyx** [comment]
I actually think all of the above makes good intro material. We're not trying to sell anything, and I think these things are perfect for whetting people's curiosity.

**Comment by wobh** [comment]
How I hate that ESR quote. Not wild about the Kay one either, although years later (only recently, really) I've come to see why he said that. I'm glad they've been brought up though, because it reminds me that there's an astonishing amount of CL and general Lisp hype and antihype, written over the decades which I think worth warning newbies to treat with extreme skepticism when they come across it. I feel uncomfortable adding to it, here, but we could provide a bunch of links to various things: 

- John McCarthy's _History of Lisp_: http://www-formal.stanford.edu/jmc/history/lisp/lisp.html
- Gabriel and Steele's _The Evolution of Lisp_: http://dreamsongs.com/Files/Hopl2.pdf
- Kent Pitman's _Common Lisp: the Untold Story_: http://www.nhplace.com/kent/Papers/cl-untold-story.html

Others as I think of them.

**Comment by kytrinyx** [comment]
> [T]here's an astonishing amount of CL and general Lisp hype and antihype, written over the decades which I think worth warning newbies to treat with extreme skepticism when they come across it.

Excellent point, and something that makes the language even more interesting, to my mind.

![god-used-lisp](https://cloud.githubusercontent.com/assets/276834/11460817/84f94aa8-96b1-11e5-8037-c8ad8d28c39d.jpeg)

**Comment by wobh** [comment]
Ron Garret's recent _Why Lisp_: http://blog.rongarret.info/2015/05/why-lisp.html
and rather less recent _Lisping at JPL_ http://www.flownet.com/gat/jpl-lisp.html

More Kent Pitman, answering questions from Slashdot: 
- part 1 http://developers.slashdot.org/story/01/11/03/1726251/kent-m-pitman-answers-on-lisp-and-much-more
- part 2 http://slashdot.org/story/01/11/13/0420226/Kent-M-Pitmans-Second-Wind

Peter Siebel's _Why Lisp?_ http://www.gigamonkeys.com/book/introduction-why-lisp.html introduction to _Practical Common Lisp_

Peter Norvig's preface to _Paradigms of Artificial Intelligence Programming_: http://www.norvig.com/paip-preface.html

CLISP _Propaganda: http://clisp.org/propaganda.html

Lispworks _Common Lisp - Myths and Legends_ http://www.lispworks.com/products/myths_and_legends.html

John McCarthy _Lisp-Notes on its Past and Future_ http://www-formal.stanford.edu/jmc/lisp20th/lisp20th.html

**Comment by canweriotnow** [comment]
Well, let's not forget Gabriel's _[Lisp: Good News, Bad News, How to Win Big](https://www.dreamsongs.com/WIB.html),_ aka "Worse Is Better"

Or, for that matter, Paul Graham's big Lisp essays:

[Beating The Averages](http://www.paulgraham.com/avg.html)

(Sorry, @wobh, for citing an essay that cites that ESR essay :-p)

[Revenge of The Nerds](http://www.paulgraham.com/icad.html)

I guess the answer to "why learn Common Lisp?" is "it sure beats writing Blub!"

**Comment by wobh** [comment]
I had, by no means, forgotten those. ;-)

**Comment by canweriotnow** [comment]
Any movement on this? I'd be happy to write a draft sometime this weekend and post it for comment.

**Comment by verdammelt** [comment]
Haven't had the time lately. Been trying to get back to #69 first. Feel free to take a stab at this. (assign it to yourself if you will do it).

**Comment by wobh** [comment]
Thank you!

**Comment by canweriotnow** [comment]
Sounds good. I'm going to do it from scratch in org format if no one objects, since I plan on running pandoc to org-ify the rest re #101

**Comment by verdammelt** [comment]
@canweriotnow any update?

**Comment by wobh** [comment]
Okay if I take this one over?

**Comment by wobh** [comment]
Please review ☝️ https://github.com/wobh/xlisp/commit/7de2bbda388530f6608eaf7080e97cfb3a2a7d22

**Comment by verdammelt** [comment]
@wobh Looks good. But maybe we want to add a little prompting people to give it a try.

Something about: multi-paradigm, strong function & OO facilities, clean syntax, wide standard library, macros etc.?

**Comment by verdammelt** [comment]
Hey @wobh I've decided I'd like to merge this in. Either go ahead and push your change to xlisp or submit a pull request and I'll merge.

**Comment by wobh** [comment]
Thanks! All but forgot.
