### ISSUE TITLE
triangle: incorrect test in some tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xlisp#96]
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

**Comment by verdammelt** [comment]
This track does not have this test - but would the example code would pass if we had it.

**Comment by verdammelt** [comment]
c.f. PR #97

**Comment by yurrriq** [comment]
@verdammelt, check out the discussion [here](https://github.com/exercism/xerlang/issues/85).

**Comment by yurrriq** [comment]
Based on that discussion, I decide to consider degenerate triangles "illogical" in xclojure.

**Comment by verdammelt** [comment]
Fooey: I didn't properly read the issue in the first place.

However: glad that my failure to read has led me to the 'correct' interpretation :)

And now that I think of it we have another test (1, 2, 1) which is effectively the same test as (2, 4, 2) so I'm going to withdraw the pull request.

**Comment by yurrriq** [comment]
I went through the same misreading to 'correct' interpretation process on xclojure, too.

> I'm going to withdraw the pull request

Sounds good to me. The extra test doesn't add any value.

**Comment by verdammelt** [comment]
Going to close this issue as it appears, by accident, this track was already OK.
