### ISSUE TITLE
Build failing after #98

### ISSUE THREAD

**Issue by wobh** [exercism/xlisp#99]
#98 is a much needed update to the README, so this is kind of a WTF.

~~Failing test~~ Error in Robot, https://travis-ci.org/exercism/xlisp/jobs/109074111#L907

```
INFO: Running tests for #<PACKAGE "ROBOT">
; in: LAMBDA ()
;     (LISP-UNIT:ASSERT-TRUE
;      (AND (= (LENGTH ROBOT-NAME-TEST::NAME) 5)
;           (EVERY #'ROBOT-NAME-TEST::IS-UPPER-ALPHA-P
;                  (SUBSEQ ROBOT-NAME-TEST::NAME 0 2))
;           (EVERY #'ROBOT-NAME-TEST::IS-DIGIT-P
;                  (SUBSEQ ROBOT-NAME-TEST::NAME 2 5))))
; --> LISP-UNIT::EXPAND-T-OR-F LET 
; ==>
;   #'AND
; 
; caught ERROR:
;   The macro name AND was found as the argument to FUNCTION.
; 
; compilation unit finished
;   caught 1 ERROR condition
 | Execution error:
 | Execution of a form compiled with errors.
Form:
  #'AND
Compile-time error:
  The macro name AND was found as the argument to FUNCTION.
 |
NAME-MATCHES-EXPECTED-PATTERN: 0 assertions passed, 0 failed, and an execution error.
```

EDIT: ~~And this is weird~~

https://travis-ci.org/exercism/xlisp/jobs/109074111#L1489

EDIT: removed SBCL warnings about undefined functions in the atbash-cipher example. This is normal since SBCL warns about this if the reference comes before the definition in the file. We may want to specify an example style guideline about this but it's not a problem. From https://travis-ci.org/exercism/xlisp/jobs/109074111#L1554 on down the atbash tests run fine.

**Comment by verdammelt** [comment]
Hmm could there be some issue with an updated dependency between the last good build and this one? (I kicked off a rebuild before seeing this - i'm assuming it is going to fail). Perhaps SBCL and/or lisp-unit updated?

**Comment by verdammelt** [comment]
(scene: a SLIME SBCL REPL)
>  CL-USER> (ql:update-all-dists)
> ...
> ==================================================
> 172,166 bytes in 0.28 seconds (606.97KB/sec)
> ; Fetching #<URL "http://beta.quicklisp.org/archive/lisp-unit/2016-02-08/lisp-unit-20160208-git.tgz">
> ; 17.48KB
> ==================================================
> ...
> CL-USER> (load "robot-name-test.lisp")
>
> To load "lisp-unit":
>   Load 1 ASDF system:
>     lisp-unit
> ; Loading "lisp-unit"
> 
> ; in: LAMBDA ()
> ;     (LISP-UNIT:ASSERT-TRUE
> ;      (AND (= (LENGTH ROBOT-NAME-TEST::NAME) 5)
> ;           (EVERY #'ROBOT-NAME-TEST::IS-UPPER-ALPHA-P
> ;                  (SUBSEQ ROBOT-NAME-TEST::NAME 0 2))
> ;           (EVERY #'ROBOT-NAME-TEST::IS-DIGIT-P
> ;                  (SUBSEQ ROBOT-NAME-TEST::NAME 2 5))))
> ; --> LISP-UNIT::EXPAND-T-OR-F LET 
> ; ==>
> ;   #'AND
> ; 
> ; caught ERROR:
> ;   The macro name AND was found as the argument to FUNCTION.
> ; 
> ; compilation unit finished
> ;   caught 1 ERROR condition
>  | Execution error:
>  | Execution of a form compiled with errors.
> Form:
>   #'AND
> Compile-time error:
>   The macro name AND was found as the argument to FUNCTION.

Looks like the problem is reproducable with the new version of lisp-unit. Happy Valentine's Day!

**Comment by wobh** [comment]
Ha! Jinx!

**Comment by verdammelt** [comment]
Quick scan of lisp-unit makes it look like there has been some "refactoring" done - and now it assumes that the argument to `assert-true` (and others) is a functional call form (e.g. `(fn arg1 arg2...)` if it is not an atom.

*sigh*

We should have snapshotted lisp-unit and checked it into the repo.

**Comment by wobh** [comment]
I wondered if we could specify a version of lisp-unit to use between quicklisp and travisci, but based on what I've gleaned, no.

**Comment by wobh** [comment]
Sorry to keep closing and reopening. On a phone.

**Comment by wobh** [comment]
Ugh.

**Comment by verdammelt** [comment]
I think I have a fix. Workaround really. Going to try to spend a little time with lisp-unit to figure out what changed and perhaps even *why*. Perhaps send a pull request etc. etc.
